<a href="https://colab.research.google.com/github/ValentinaGiraldo0/Code_in_class/blob/main/03_Data_Structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What us a data structure?**

DS are like variable, they *save* information. The difference is that DS can store more than 1 value.

Formally, DS store a **sequence** of values which can be located with an index 
(sciling). Ex: List, vectors and matrices, databases.

Now, basic Python sucks!! It lacks specialized tools, In this case, we need to install `numpy`.

# **2. Linear Algebra - Numpy**


## 2.1. **What is Numpy?**

Numpy (or Numerical Python) is collection of functions and methods to handle DS. 

This library works very well with other libraries and it is very popular.

In [7]:
# Install a library 

import numpy as np

## 2.2. Numpy arrays - vector and matrices

Objects arranged by row and columns. With these object you can sum and multiply.

*Example 1*

Let $b$ be a vector with 2 rows and 1 column:

\begin{equation}
a = \left[\begin{array}{c} a_{1} \\ a_{2}
    \end{array}\right]
\end{equation}

This is called a **COLUMN VECTOR**. And the dimension or shape is $(2,1)$ or $(2 \times 1)$



*Example 2*

Let $b$ be a vector with 1 rows and 2 column:

\begin{equation}
b = \left[\begin{array}{c} b_{1} & b_{2}
    \end{array}\right]
\end{equation}

This is called a **ROW VECTOR**. And the dimension or shape is $(1,2)$ or $(1 \times 2)$


*Example 3*

A matrix has more than 1 row and more than column.

Of course if the number rows and columns are equal, it is called a *squared matrix*.

In general, let $M$ be a matrix of dimensions $(n,m)$ or $(n \times m)$.

For the case of $n=3$ and $m=3$:

\begin{equation}
M = \left[\begin{array}{c}
m_{1,1} & m_{1,2} & m_{1,3} \\
m_{2,1} & m_{2,2} & m_{2,3} \\
m_{3,1} & m_{3,2} & m_{3,3} \\
    \end{array}\right]
\end{equation}


Now, all of this 

In [8]:
# Example - Column Vector 

a = np.array([[4],[5],[6]])
print(a)
print(a.shape)

[[4]
 [5]
 [6]]
(3, 1)


In [9]:
# Example - Row Vector 

b = np.array([[1,2,3]])
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


In [10]:
# Example - Matrix

M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


**A nice trick**



In [11]:
# nr: Stores the number of rows
# nc: Stores the number of columns
nr, nc = M.shape

**Size od DS**

In Python, *size* means the number of elemenets in a DS.

In [12]:
M.size

9

In [13]:
# ONE WARNING

z = 2
w = np.array([[2]])
print(type(z),type(w))


<class 'int'> <class 'numpy.ndarray'>


## 2.3. Slicing

It is the same as string variable, only with minor modificationes.

Let's see:



In [14]:
# Extract the 1st element

## Column Vector 
print(a[0,0])
print(type(a[0,0]))

## Row Vector 
print(b[0,0])
print(type(a[0,0]))

#Matrix
print(M[1,1])

4
<class 'numpy.int64'>
1
<class 'numpy.int64'>
5


In [15]:
# Extract the last element

print('The last element of a row vector:', b[0,-1])
print('The last element of a column vector:', a[-1,0])
print('The last element of a matrix:', M[-1,-1])

The last element of a row vector: 3
The last element of a column vector: 6
The last element of a matrix: 9


In [16]:
# Extract a subset 

## Column Vector
print(a[0:2])

## Row Vector 
print(b[0,0:2])

## Matrix
print(M[0:2,0:2])

[[4]
 [5]]
[1 2]
[[1 2]
 [4 5]]


## 2.4. Useful methods

### Zeros ans Ones



In [17]:
# Create a row vector of 0's (1,7)
# z1 = np.array([[0,0,0,0,0,0,0]])

# Zeros

## One dimensional
z1 = np.zeros(7)
print(z1)

z2 = np.zeros(7, dtype = int)
print(z2)

## Two dimensional 
Z1 = np.zeros((4,5))
print(Z1)


[0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Ones

## One dimensional
o1 = np.ones(7)
print(o1)

o2 = np.ones(7, dtype = int)
print(o2)

## Two dimensional 
O1 = np.ones((4,5))
print(O1)


[1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Another creation options



In [ ]:
# Full

## One dimension
np.full(7,13)

## Two dimension 
np.full((3,2),13)

array([[13, 13],
       [13, 13],
       [13, 13]])

In [ ]:
# A DS with space values (like a sequence)

## A custom sequence - only can create one dimension
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
## A custom sequence - starting with a and stop at b
a = 3
b = 25
np.arange(a,b)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [ ]:
## A custom sequence with a set step
a = 3
b = 25
s = 0.25 #step
np.arange(a,b,s)

array([ 3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,  5.  ,
        5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,
        7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,
        9.75, 10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 , 11.75,
       12.  , 12.25, 12.5 , 12.75, 13.  , 13.25, 13.5 , 13.75, 14.  ,
       14.25, 14.5 , 14.75, 15.  , 15.25, 15.5 , 15.75, 16.  , 16.25,
       16.5 , 16.75, 17.  , 17.25, 17.5 , 17.75, 18.  , 18.25, 18.5 ,
       18.75, 19.  , 19.25, 19.5 , 19.75, 20.  , 20.25, 20.5 , 20.75,
       21.  , 21.25, 21.5 , 21.75, 22.  , 22.25, 22.5 , 22.75, 23.  ,
       23.25, 23.5 , 23.75, 24.  , 24.25, 24.5 , 24.75])

In [ ]:
## Linear space 
a = 15
b = 17
n = 10

np.linspace(a, b, num = n)


array([15.        , 15.22222222, 15.44444444, 15.66666667, 15.88888889,
       16.11111111, 16.33333333, 16.55555556, 16.77777778, 17.        ])

### Random numbers 

We are talking about probabilities, and of probabilitic distributions. 

### Uniform distribution over [0,1)

In [ ]:
# A Single vale
np.random.rand()

0.42361930156855787

In [ ]:
# Example - The coin toss
# Here we are going to similate a coin toss

if np.random.rand() <= 0.5:
  print('head')
else:
  print('tails')

head


In [ ]:
# Example 2 - Ranking 

## The idea is to print 'Low' if the number is lower than 0.3
## print 'Average' if is between 0.3 and 0.7
## print 'High' if it is greater than 0.7

rnd = np.random.rand()

if np.random.rand() <=0.3:
  print('Low')
elif np.random.rand() > 0.3 and rnd <=0.7:
  print('Average',rnd)
else:
  print('High',rnd)

Average 0.4661345969642485


**Exersice**

Code the following game: Print the message 'You win!' if two coin tosses are heads and print 'You lose!' otherwise.

In [18]:
# Solution Exercise
## First Try (or attempt)

First_attempt = np.random.rand()

if First_attempt <=0.5:
  print('Head', First_attempt)
else:
  print('Tails', First_attempt)

## Second Try (or attempt)

Second_attempt = np.random.rand()

if Second_attempt <=0.5:
  print('Head', Second_attempt)
else:
  print('Tails', Second_attempt)

if First_attempt <=0.5 and Second_attempt <=0.5:
  print('You Win!')
else:
  print('You Lose')


Tails 0.8450903291038457
Tails 0.6705409380526818
You Lose


In [21]:
# Solucion 3.0

tries = np.random.rand(2)

results = np.array([['Head', 'Tails']])
indx1 = int(round(tries[0],0))
indx2 = int(round(tries[1],0))

if tries[0] <=0.5 and tries[1] <=0.5:
  print('Head', tries[0])
  print('Head', tries[1])
  print('You win!')
else:
  print(results[0,indx1], tries[0])
  print(results[0,indx2], tries[1])
  print('You lose!')

Tails 0.8327323659587755
Head 0.3621677185956419
You lose!


In [29]:
# One dimensional array
np.random.rand(4)

array([0.07520277, 0.96669549, 0.8675424 , 0.53829946])

In [22]:
# Two dimensional arrays
np.random.rand(7,8)

array([[2.38765305e-01, 8.34314370e-01, 5.03829589e-01, 8.69353860e-01,
        4.28701209e-01, 5.44035028e-01, 3.65689356e-02, 3.59884249e-02],
       [2.66681653e-02, 5.65304935e-01, 1.24244314e-01, 3.90240428e-01,
        5.86570325e-01, 6.10754186e-01, 1.42867049e-01, 7.98679202e-01],
       [8.66769702e-02, 7.59644620e-01, 8.67481132e-01, 4.50756359e-01,
        3.75374545e-01, 4.32726894e-01, 3.20659165e-01, 7.02812556e-01],
       [6.91761817e-01, 7.10063639e-01, 7.85299483e-02, 7.68859233e-01,
        4.21732283e-01, 2.57594195e-01, 9.21439757e-01, 9.09423943e-01],
       [5.46571164e-01, 7.63140457e-01, 2.90323638e-01, 3.02374594e-02,
        5.92067220e-02, 1.41667293e-01, 3.38527705e-01, 9.08624775e-01],
       [2.94570810e-03, 4.52610014e-01, 7.80733626e-01, 8.64098403e-01,
        7.05502277e-01, 9.53390168e-02, 7.16944162e-01, 4.35080268e-01],
       [2.23183863e-02, 4.18141760e-04, 6.80894829e-01, 5.52925430e-01,
        2.60752755e-01, 6.38591256e-01, 4.53055155e-01, 6.

### Uniform distribution over [a,b)

In [23]:
# One value
np.random.uniform(low= 10, high = 0)

8.869383680098714

In [24]:
# One dimensional
np.random.uniform(low= 10, high = 5, size = 10)

array([8.82565497, 5.93336808, 9.55929111, 9.34312288, 7.99387007,
       5.7178033 , 6.21008711, 5.1129698 , 9.61127458, 9.55158231])

In [25]:
# Two dimensional

np.random.uniform(low= -10, high = 0, size = (4,2))

array([[-8.42238706, -4.84744089],
       [-7.99588096, -4.31447224],
       [-2.80368979, -0.44387021],
       [-8.02965056, -1.79682586]])

## 2.5. Normal Distribution

In [26]:
# Standard Normal - N ~ (0,1)
np.random.randn()
np.random.randn(8)
np.random.randn(7,5)

array([[ 0.63217094, -0.39649796,  0.42276858, -0.36916434,  1.55944907],
       [-0.90923423,  0.70019901,  1.16720372, -1.6908443 ,  0.306485  ],
       [ 0.5261824 ,  0.56000262, -1.83877917, -1.01343961, -0.07153136],
       [-0.39563617,  0.88670752,  1.10436215,  1.01229264,  1.81676016],
       [-1.23613039,  2.64497621, -0.42915488,  0.63452572,  0.04250248],
       [ 0.0767799 , -0.25222375, -1.55258789, -0.05377425, -0.18351609],
       [ 1.22219164,  0.59986341,  1.09156021,  1.08658029,  1.72431299]])

In [27]:
# Normal - N ~ (mu, sigma)

mu = 0.001 # mean
sigma = 0.1 # std. deviation

np.random.normal(mu, sigma)
np.random.normal(mu, sigma, size = 5)
np.random.normal(mu, sigma, size = (3,1))

array([[-0.04328039],
       [ 0.02316034],
       [ 0.06492925]])

### Random Integer

In [28]:
np.random.randint(low = 0, high = 10 ) # one value
np.random.randint(low = 0, high = 10,  size = 8 ) # one dimension
np.random.randint(low = 0, high = 10,  size = (2,3)) # Two dimensions

array([[8, 2, 3],
       [5, 2, 6]])