<a href="https://colab.research.google.com/github/ValentinaGiraldo0/Code_in_class/blob/main/03_Data_Structures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What us a data structure?**

DS are like variable, they *save* information. The difference is that DS can store more than 1 value.

Formally, DS store a **sequence** of values which can be located with an index 
(sciling). Ex: List, vectors and matrices, databases.

Now, basic Python sucks!! It lacks specialized tools, In this case, we need to install `numpy`.

# **2. Linear Algebra - Numpy**


## 2.1. **What is Numpy?**

Numpy (or Numerical Python) is collection of functions and methods to handle DS. 

This library works very well with other libraries and it is very popular.

In [4]:
# Install a library 

import numpy as np

## 2.2. Numpy arrays - vector and matrices

Objects arranged by row and columns. With these object you can sum and multiply.

*Example 1*

Let $b$ be a vector with 2 rows and 1 column:

\begin{equation}
a = \left[\begin{array}{c} a_{1} \\ a_{2}
    \end{array}\right]
\end{equation}

This is called a **COLUMN VECTOR**. And the dimension or shape is $(2,1)$ or $(2 \times 1)$



*Example 2*

Let $b$ be a vector with 1 rows and 2 column:

\begin{equation}
b = \left[\begin{array}{c} b_{1} & b_{2}
    \end{array}\right]
\end{equation}

This is called a **ROW VECTOR**. And the dimension or shape is $(1,2)$ or $(1 \times 2)$


*Example 3*

A matrix has more than 1 row and more than column.

Of course if the number rows and columns are equal, it is called a *squared matrix*.

In general, let $M$ be a matrix of dimensions $(n,m)$ or $(n \times m)$.

For the case of $n=3$ and $m=3$:

\begin{equation}
M = \left[\begin{array}{c}
m_{1,1} & m_{1,2} & m_{1,3} \\
m_{2,1} & m_{2,2} & m_{2,3} \\
m_{3,1} & m_{3,2} & m_{3,3} \\
    \end{array}\right]
\end{equation}


Now, all of this 

In [ ]:
# Example - Column Vector 

a = np.array([[4],[5],[6]])
print(a)
print(a.shape)

[[4]
 [5]
 [6]]
(3, 1)


In [ ]:
# Example - Row Vector 

b = np.array([[1,2,3]])
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


In [ ]:
# Example - Matrix

M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


**A nice trick**



In [ ]:
# nr: Stores the number of rows
# nc: Stores the number of columns
nr, nc = M.shape

**Size od DS**

In Python, *size* means the number of elemenets in a DS.

In [ ]:
M.size

9

In [ ]:
# ONE WARNING

z = 2
w = np.array([[2]])
print(type(z),type(w))


<class 'int'> <class 'numpy.ndarray'>


array([[1.]])

## 2.3. Slicing

It is the same as string variable, only with minor modificationes.

Let's see:



In [ ]:
# Extract the 1st element

## Column Vector 
print(a[0,0])
print(type(a[0,0]))

## Row Vector 
print(b[0,0])
print(type(a[0,0]))

#Matrix
print(M[1,1])

4
<class 'numpy.int64'>
1
<class 'numpy.int64'>
5


In [ ]:
# Extract the last element

print('The last element of a row vector:', b[0,-1])
print('The last element of a column vector:', a[-1,0])
print('The last element of a matrix:', M[-1,-1])

The last element of a row vector: 3
The last element of a column vector: 6
The last element of a matrix: 9


In [ ]:
# Extract a subset 

## Column Vector
print(a[0:2])

## Row Vector 
print(b[0,0:2])

## Matrix
print(M[0:2,0:2])

[[4]
 [5]]
[1 2]
[[1 2]
 [4 5]]


## 2.4. Useful methods

### Zeros ans Ones



In [9]:
# Create a row vector of 0's (1,7)
# z1 = np.array([[0,0,0,0,0,0,0]])

# Zeros

## One dimensional
z1 = np.zeros(7)
print(z1)

z2 = np.zeros(7, dtype = int)
print(z2)

## Two dimensional 
Z1 = np.zeros((4,5))
print(Z1)


[0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
# Ones

## One dimensional
o1 = np.ones(7)
print(o1)

o2 = np.ones(7, dtype = int)
print(o2)

## Two dimensional 
O1 = np.ones((4,5))
print(O1)


[1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Another creation options



In [14]:
# Full

## One dimension
np.full(7,13)

## Two dimension 
np.full((3,2),13)

array([[13, 13],
       [13, 13],
       [13, 13]])

In [15]:
# A DS with space values (like a sequence)

## A custom sequence - only can create one dimension
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [16]:
## A custom sequence - starting with a and stop at b
a = 3
b = 25
np.arange(a,b)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [21]:
## A custom sequence with a set step
a = 3
b = 25
s = 0.25 #step
np.arange(a,b,s)

array([ 3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,  5.  ,
        5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,
        7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,
        9.75, 10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 , 11.75,
       12.  , 12.25, 12.5 , 12.75, 13.  , 13.25, 13.5 , 13.75, 14.  ,
       14.25, 14.5 , 14.75, 15.  , 15.25, 15.5 , 15.75, 16.  , 16.25,
       16.5 , 16.75, 17.  , 17.25, 17.5 , 17.75, 18.  , 18.25, 18.5 ,
       18.75, 19.  , 19.25, 19.5 , 19.75, 20.  , 20.25, 20.5 , 20.75,
       21.  , 21.25, 21.5 , 21.75, 22.  , 22.25, 22.5 , 22.75, 23.  ,
       23.25, 23.5 , 23.75, 24.  , 24.25, 24.5 , 24.75])

In [27]:
## Linear space 
a = 15
b = 17
n = 10

np.linspace(a, b, num = n)


array([15.        , 15.22222222, 15.44444444, 15.66666667, 15.88888889,
       16.11111111, 16.33333333, 16.55555556, 16.77777778, 17.        ])

### Random numbers 

We are talking about probabilities, and of probabilitic distributions. 

#### Uniform distribution over [0,1)

In [29]:
# A Single vale
np.random.rand()

0.42361930156855787

In [38]:
# Example - The coin toss
# Here we are going to similate a coin toss

if np.random.rand() <= 0.5:
  print('head')
else:
  print('tails')

head


In [44]:
# Example 2 - Ranking 

## The idea is to print 'Low' if the number is lower than 0.3
## print 'Average' if is between 0.3 and 0.7
## print 'High' if it is greater than 0.7

rnd = np.random.rand()

if np.random.rand() <=0.3:
  print('Low')
elif np.random.rand() > 0.3 and rnd <=0.7:
  print('Average',rnd)
else:
  print('High',rnd)

Average 0.4661345969642485


**Exersice**

Code the following game: Print the message 'You win!' if two coin tosses are heads and print 'You lose!' otherwise.

In [59]:
# Solution Exercise
## First Try (or attempt)

First_attempt = np.random.rand()

if First_attempt <=0.5:
  print('Head', First_attempt)
else:
  print('Tails', First_attempt)

## Second Try (or attempt)

Second_attempt = np.random.rand()

if Second_attempt <=0.5:
  print('Head', Second_attempt)
else:
  print('Tails', Second_attempt)

if First_attempt <=0.5 and Second_attempt <=0.5:
  print('You Win!')
else:
  print('You Lose')


Head 0.4642473938773658
Head 0.11658286783541594
You Win!
